# Generated by Django 4.2.9 on 2024-07-10 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=10)),
                ('stock_code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.FloatField()),
                ('customer_id', models.CharField(max_length=10)),
                ('region', models.CharField(max_length=100)),
                ('invoice_day', models.IntegerField()),
                ('invoice_month', models.IntegerField()),
                ('invoice_year', models.IntegerField()),
                ('invoice_hour', models.IntegerField()),
                ('total_sales', models.FloatField()),
                ('sales_per_customer', models.FloatField()),
                ('invoices_per_customer', models.FloatField()),
                ('avg_sales_per_customer', models.FloatField()),
                ('neg_invoices_per_customer', models.FloatField()),
            ],
        ),
    ]
