# Generated by Django 4.2.9 on 2024-07-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvdata',
            name='neg_invoices_per_customer',
            field=models.IntegerField(),
        ),
    ]
