# Generated by Django 4.2.9 on 2024-07-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_uploader', '0002_alter_csvdata_neg_invoices_per_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvdata',
            name='invoices_per_customer',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='sales_per_customer',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='total_sales',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
